check if json file is readable

diff --git a/misc/yta-raw b/misc/yta-raw
--- a/misc/yta-raw
+++ b/misc/yta-raw
@@ -9,6 +9,11 @@ fi
 json="$1"
 shift
 
+if [ ! -r "$json" ]; then
+    echo "Unable to read file '$json'" 1>&2;
+    exit 1;
+fi
+
 q() {
     cat "$json" | jq .metadata | jq --raw-output "$1"
 }
